In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv("movie_genres.csv", index_col=0)
users = pd.read_csv("user_reviews.csv", index_col=0)

In [3]:
movies.head()

,movie_title,genre_action,genre_adventure,genre_animation,genre_biography,genre_comedy,genre_crime,genre_documentary,genre_drama,genre_family,...,genre_music,genre_musical,genre_mystery,genre_romance,genre_sci-fi,genre_short,genre_sport,genre_thriller,genre_war,genre_western
0,Marilyn Hotchkiss' Ballroom Dancing and Charm ...,0,0,0,0,1,0,0,0,1,...,0,1,0,1,0,1,0,0,0,0
1,Fair Game,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
2,The Wild Bunch,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,Little Nicholas,0,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,Æon Flux,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [4]:
users.head()

,User,Marilyn Hotchkiss' Ballroom Dancing and Charm School,Fair Game,The Wild Bunch,Little Nicholas,Æon Flux,Water for Elephants,Dave Chappelle's Block Party,The Wolf of Wall Street,Dracula Untold,...,Executive Decision,Gigli,Mean Streets,Inkheart,Just Married,The Sleepwalker,Monte Carlo,The Misfits,Children of Men,Blood Ties
0,Vincent,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Edgar,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Addilyn,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Marlee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Javier,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [71]:
def get_rating(user_ratings, user, movie):
    return user_ratings.iloc[user][movie]

def average_rating(user_ratings, movie):
    summ = user_ratings[movie].sum(axis=0)
    return summ/(user_ratings.astype(bool)[movie].sum(axis=0))

def recommend_movies(users, movies, user, n_predictions):
    corr_movies = movies.set_index("movie_title").T.corr()
    #corr_movies = corr_movies.rename(columns={ corr_movies.columns[1]: "movie_title" })
    #corr_movies["movie_title"].keys().values
    rated_movies = users.iloc[user][users.iloc[user]!=0]
    unrated_movies = users.iloc[user][users.iloc[user]==0]
    
    keys = rated_movies.keys()[1:]
    relevant_movies = corr_movies[keys]
    
    predictions = {} 
    for i in unrated_movies.keys().values: 
        baseline = average_rating(users, i)
        related_movies = relevant_movies[relevant_movies.index == i]
        related_movies = related_movies[related_movies > 0.45].dropna(axis=1)
        summ = 0
        summ2 = 0
        for key, value in related_movies.iteritems(): 
            #print(get_rating(users, user, key))
            #print(average_rating(users, key))
            summ += value[0]*(get_rating(users, user, key) - average_rating(users, key)) 
            summ2 += value[0]
            
        if summ2 == 0:
            predictions[i] = 0
        else:
            predictions[i] = baseline + (summ / summ2)
    return sorted(predictions.items(), key=lambda x: x[1], reverse=True)[0:n_predictions]

In [76]:
recommend_movies(users, movies, 4, 5)

[('Abandon', 5.525),
 ('Blade II', 5.142857142857142),
 ('Meet Joe Black', 5.126201730178953),
 ('The Pink Panther', 5.081818181818182),
 ('Open Water', 5.041214262725395)]

In [299]:
users.mean().sort_valus(ascending=False)

Contraband                      0.150000
Breakdown                       0.146667
American Splendor               0.138333
Miracle at St. Anna             0.136667
Escobar: Paradise Lost          0.133333
                                  ...
Scott Walker: 30 Century Man    0.006667
Jennifer's Body                 0.005000
Happy Gilmore                   0.005000
Mooz-Lum                        0.001667
The Little Ponderosa Zoo        0.001667
Length: 2000, dtype: float64

In [21]:
corr_movies = movies.set_index("movie_title").T.corr()

In [22]:
corr_movies["Fair Game"]["Fair Game"]

1.0

In [23]:

#corr_movies['movie_title'] = corr_movies.index
corr_movies.head()

movie_title,Marilyn Hotchkiss' Ballroom Dancing and Charm School,Fair Game,The Wild Bunch,Little Nicholas,Æon Flux,Water for Elephants,Dave Chappelle's Block Party,The Wolf of Wall Street,Dracula Untold,A Bridge Too Far,...,Executive Decision,Gigli,Mean Streets,Inkheart,Just Married,The Sleepwalker,Monte Carlo,The Misfits,Children of Men,Blood Ties
movie_title,,,,,,,,,,,,,,,,,,,,,
Marilyn Hotchkiss' Ballroom Dancing and Charm School,1.000000,-0.204124,-0.204124,0.585540,-0.162650,0.211445,0.108866,0.036274,-0.277778,-0.204124,...,-0.204124,0.421857,0.036274,0.108866,0.585540,-0.112367,0.592472,0.108866,-0.204124,-0.204124
Fair Game,-0.204124,1.000000,-0.150000,-0.119523,-0.119523,0.338648,-0.150000,0.503497,0.108866,0.233333,...,0.233333,-0.150000,0.503497,-0.150000,-0.119523,0.550482,-0.177705,0.233333,0.616667,0.616667
The Wild Bunch,-0.204124,-0.150000,1.000000,-0.119523,0.338648,-0.119523,-0.150000,-0.177705,0.108866,-0.150000,...,0.616667,-0.150000,-0.177705,0.233333,-0.119523,-0.082572,0.162896,0.233333,-0.150000,-0.150000
Little Nicholas,0.585540,-0.119523,-0.119523,1.000000,-0.095238,-0.095238,0.338648,0.265497,-0.162650,-0.119523,...,-0.119523,0.338648,-0.141598,0.338648,0.452381,-0.065795,0.672593,-0.119523,-0.119523,-0.119523
Æon Flux,-0.162650,-0.119523,0.338648,-0.095238,1.000000,-0.095238,-0.119523,-0.141598,0.211445,-0.119523,...,0.338648,-0.119523,-0.141598,-0.119523,-0.095238,-0.065795,-0.141598,-0.119523,0.338648,-0.119523

In [24]:
#corr_movies = corr_movies.rename(columns={ corr_movies.columns[1]: "movie_title" })

In [25]:
corr_movies.index.values

array(["Marilyn Hotchkiss' Ballroom Dancing and Charm School",
       'Fair Game', 'The Wild Bunch', ..., 'The Misfits',
       'Children of Men', 'Blood Ties'], dtype=object)

In [26]:
corr_movies.index.values

array(["Marilyn Hotchkiss' Ballroom Dancing and Charm School",
       'Fair Game', 'The Wild Bunch', ..., 'The Misfits',
       'Children of Men', 'Blood Ties'], dtype=object)

In [27]:
keys.values

NameError: name 'keys' is not defined

In [53]:
rated_movies = users.iloc[0][users.iloc[0]!=0]
unrated_movies = users.iloc[0][users.iloc[0]==0]

In [54]:
rated_movies

User                                                      Vincent
Aliens vs. Predator: Requiem                                    3
Alexander                                                       4
Paris, je t'aime                                                4
The Book of Life                                                3
The Best Man                                                    5
One Day                                                         5
Zack and Miri Make a Porno                                      3
The Great Escape                                                5
The Celebration                                                 3
The X Files: I Want to Believe                                  4
Home Run                                                        4
Cargo                                                           3
Old Dogs                                                        2
Sweet Sweetback's Baadasssss Song                               4
G.I. Joe: Retaliation                                           1
First Blood                                                     5
At First Sight                                                  4
The Big Hit                                                     3
Draft Day                                                       5
Sinister 2                                                      2
A Tale of Three Cities                                          5
Flatliners                                                      5
The Horseman on the Roof                                        5
Alien 3                                                         3
The Pirates Who Don't Do Anything: A VeggieTales Movie          4
The Man with the Iron Fists                                     1
Song One                                                        5
Twisted                                                         4
The Nutty Professor                                             1
Miracles from Heaven                                            5
Valley of the Heart's Delight                                   3
Dry Spell                                                       1
Footloose                                                       5
Ri¢hie Ri¢h                                                     3
Secret in Their Eyes                                            5
Total Recall                                                    3
Name: 0, dtype: object

In [55]:
unrated_movies.keys().values

array(["Marilyn Hotchkiss' Ballroom Dancing and Charm School",
       'Fair Game', 'The Wild Bunch', ..., 'The Misfits',
       'Children of Men', 'Blood Ties'], dtype=object)

In [58]:
keys = rated_movies.keys()[1:]
keys_unrated = unrated_movies.keys()[1:]

In [59]:
relevant_movies = corr_movies[keys]

In [66]:
#relevant_movies[relevant_movies["movie_title"].keys().isin(keys_unrated)][]
#relevant_movies[relevant_movies["movie_title"].str.match("Fair Game")]
#relevant_movies[relevant_movies["movie_title"].str.match("Fair Game")]
related_movies = relevant_movies[relevant_movies.index == "Dracula Untold"]

In [69]:
test = related_movies[related_movies > 0.1].dropna(axis=1)

In [70]:
test

movie_title,Aliens vs. Predator: Requiem,Alexander,"Paris, je t'aime",The Best Man,One Day,The Great Escape,The Celebration,Home Run,Sweet Sweetback's Baadasssss Song,First Blood,...,Flatliners,The Horseman on the Roof,Alien 3,The Man with the Iron Fists,Song One,Twisted,Miracles from Heaven,Valley of the Heart's Delight,Footloose,Total Recall
movie_title,,,,,,,,,,,,,,,,,,,,,
Dracula Untold,0.314373,0.338648,0.108866,0.211445,0.211445,0.233333,0.40452,0.211445,0.108866,0.421857,...,0.314373,0.314373,0.421857,0.40452,0.211445,0.108866,0.40452,0.40452,0.108866,0.211445

In [138]:
for key, value in test.iteritems(): 
    print(value[0])

0.5034965460952286

In [45]:
relevant_movies["movie_title"].keys()

KeyError: 'movie_title'

In [46]:
users_ = users.drop("User", axis=1)
#users_ = users_.drop("Unnamed: 0", axis=1)

In [47]:
users_.head()

,Marilyn Hotchkiss' Ballroom Dancing and Charm School,Fair Game,The Wild Bunch,Little Nicholas,Æon Flux,Water for Elephants,Dave Chappelle's Block Party,The Wolf of Wall Street,Dracula Untold,A Bridge Too Far,...,Executive Decision,Gigli,Mean Streets,Inkheart,Just Married,The Sleepwalker,Monte Carlo,The Misfits,Children of Men,Blood Ties
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
correlations = users.corrwith(users["Fair Game"])

In [25]:
correlations.sort_values(ascending=False).head()

Fair Game         1.000000
Rock Star         0.416876
All or Nothing    0.386332
Prom Night        0.352230
Set It Off        0.328462
dtype: float64

In [86]:
correlations = rated_movies.corrwith(rated_movies)

In [93]:
movies.corrwith(movies)

genre_action         1.0
genre_adventure      1.0
genre_animation      1.0
genre_biography      1.0
genre_comedy         1.0
genre_crime          1.0
genre_documentary    1.0
genre_drama          1.0
genre_family         1.0
genre_fantasy        1.0
genre_film-noir      1.0
genre_history        1.0
genre_horror         1.0
genre_music          1.0
genre_musical        1.0
genre_mystery        1.0
genre_romance        1.0
genre_sci-fi         1.0
genre_short          1.0
genre_sport          1.0
genre_thriller       1.0
genre_war            1.0
genre_western        1.0
dtype: float64

In [ ]:
def make_recommendation(userID, users, movies):
    corr_movies = movies.set_index("movie_title").T.corr()
    corr_movies = corr_movies.rename(columns={ corr_movies.columns[1]: "movie_title" })
    rated_movies = users.iloc[userID][users.iloc[0]!=0]
    keys = rated_movies.keys()[1:]

In [30]:
users.head()

,User,Marilyn Hotchkiss' Ballroom Dancing and Charm School,Fair Game,The Wild Bunch,Little Nicholas,Æon Flux,Water for Elephants,Dave Chappelle's Block Party,The Wolf of Wall Street,Dracula Untold,...,Executive Decision,Gigli,Mean Streets,Inkheart,Just Married,The Sleepwalker,Monte Carlo,The Misfits,Children of Men,Blood Ties
0,Vincent,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Edgar,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Addilyn,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Marlee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Javier,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [54]:
users_[users_ == None] = 0.0

In [55]:
users_.head()

,Marilyn Hotchkiss' Ballroom Dancing and Charm School,Fair Game,The Wild Bunch,Little Nicholas,Æon Flux,Water for Elephants,Dave Chappelle's Block Party,The Wolf of Wall Street,Dracula Untold,A Bridge Too Far,...,Executive Decision,Gigli,Mean Streets,Inkheart,Just Married,The Sleepwalker,Monte Carlo,The Misfits,Children of Men,Blood Ties
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
import scipy
#users_.head()
test = scipy.sparse.csr_matrix(users_.values)

In [75]:
from scipy.sparse.linalg import svds 
U, sigma, Vt = svds(test, k = 300)

In [76]:
sigma = np.diag(sigma)

In [77]:
pred = np.dot(np.dot(U, sigma), Vt)

In [78]:
preds.head()

,Marilyn Hotchkiss' Ballroom Dancing and Charm School,Fair Game,The Wild Bunch,Little Nicholas,Æon Flux,Water for Elephants,Dave Chappelle's Block Party,The Wolf of Wall Street,Dracula Untold,A Bridge Too Far,...,Executive Decision,Gigli,Mean Streets,Inkheart,Just Married,The Sleepwalker,Monte Carlo,The Misfits,Children of Men,Blood Ties
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [79]:
user = 1
unrated_movies = users.iloc[user][users.iloc[user]==0].keys()

In [80]:
preds.iloc[user][unrated_movies[1:].values].sort_values()[-5:]

Be Cool                                              0.0
Doogal                                               0.0
The Legend of Hell's Gate: An American Conspiracy    0.0
Letters from Iwo Jima                                0.0
Blood Ties                                           0.0
Name: 1, dtype: float64